server:
  port: 7777
spring:
  messages:
    basename: i18n/messages
  datasource:
    url: jdbc:mysql://localhost:3306/seconds_kill?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 547717253
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #最大连接池数量
    max-active: 20
    #初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
    initial-size: 10
    # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，
    # 并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
    max-wait: 60000
    #最小连接池数量
    min-idle: 5

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    jedis:
      pool: #连接池配置
        max-active: 16 #最大活跃连接数，默认8个
        max-idle: 8 #最大空闲连接数，默认8个
        max-wait: -1 #获取连接的最大等待时间，默认-1，表示无限制，单位毫秒 默认值可能会因为获取不到连接，导致事务无法提交，数据库被锁，大量线程处于等待状态的情况
        min-idle: 0 #最小空闲连接数，默认0
  kafka:
    bootstrap-servers: 47.94.238.10:9092
    consumer:
      group-id: spike
    template:
      default-topic: SPIKE_TOPIC
    listener:
      concurrency: 5


mybatis:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mybatis/**/*Mapper.xml
  # 搜索指定包别名
  type-aliases-package: com.liuwy.dao
logging:
  config: classpath:log4j2.xml
  level:
    root: INFO
    com.liuwy: DEBUG
spike.common:
  ##kafka配置
  kafka:
    broker.address: 10.100.1.65:9092
    listener.pollTimeout: 10000 #单位ms
    #生产者配置
    producer:
      #kafka最大请求字节数，单位字节
      max_request_size: 33554432
    consumer:
      groupId: spike
    records:
      task:
        size: 500
  receive:
    commitSize: 500

  jms:
    #消息队列kafka
    type: kafka
    #一次读取kafka的最大时间
    consumer.wait: 200
    #当发送或者消费的耗时大于该值时，打印日志
    usetime: 300
